language: java
jdk: oraclejdk8
script: mvn clean install
cache:
  directories:
  - $HOME/.m2
after_success:
- mvn jacoco:report coveralls:report
notifications:
  slack: esaude:fJniHlqocbXRRIkoDY1Ky4dw
